### ISSUE TITLE
rviz_map_plugin crash in rviz

### ISSUE THREAD

**Issue by jianhengLiu** [naturerobots/mesh_tools#19] opened 2022-11-04 12:52 UTC
The rviz crash after a period of running, give the following error messages
```
[ WARN] [1667566012.731866799]: OGRE EXCEPTION(4:ItemIdentityException): An object of type 'ManualObject' with name '0_TriangleMesh_0_7476' already exists. in SceneManager::createMovableObject at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 6829)
terminate called after throwing an instance of 'Ogre::ItemIdentityException'
  what():  OGRE EXCEPTION(4:ItemIdentityException): An object of type 'ManualObject' with name '0_TriangleMesh_0_7476' already exists. in SceneManager::createMovableObject at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 6829)
```
Any suggestion to solve this problem?
Thanks a lot!

**Comment by InguChoi** [comment] 2023-04-10 05:25
> The rviz crash after a period of running, give the following error messages
> 
> ```
> [ WARN] [1667566012.731866799]: OGRE EXCEPTION(4:ItemIdentityException): An object of type 'ManualObject' with name '0_TriangleMesh_0_7476' already exists. in SceneManager::createMovableObject at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 6829)
> terminate called after throwing an instance of 'Ogre::ItemIdentityException'
>   what():  OGRE EXCEPTION(4:ItemIdentityException): An object of type 'ManualObject' with name '0_TriangleMesh_0_7476' already exists. in SceneManager::createMovableObject at /build/ogre-1.9-kiU5_5/ogre-1.9-1.9.0+dfsg1/OgreMain/src/OgreSceneManager.cpp (line 6829)
> ```
> 
> Any suggestion to solve this problem? Thanks a lot!

Can you solve it?

**Comment by jianhengLiu** [comment] 2023-04-10 15:27
> 

you could try my fixing version: https://github.com/jianhengLiu/rviz_map_plugin

**Comment by amock** [comment] 2024-11-09 08:56
Right now the mesh tools are working with ROS 1 noetic and ROS 2 humble. I also could not reproduce this error given the information I have. So I assume it's fixed now.

Also: this is an open source project. We are happy about any fixes and making a PR afterwards :)

**Closed by amock** 2024-11-09 08:56 UTC
